"""AICE Associate 연습문제 100선.

공식 기출이 아니라 공식 출제범위(분석 30 / 전처리 30 / 모델링 40)에 맞춰 새로 만든 문제입니다.
5문제씩 20세트. check(ns)가 True를 돌려주면 정답 처리됩니다.
"""

# ── 채점 도우미 ────────────────────────────────────────────────────────────
def has(ns, name, attr=None):
    v = ns.get(name)
    if v is None:
        return False
    return hasattr(v, attr) if attr else True


def nomiss(ns, col, frame="df"):
    d = ns.get(frame)
    return d is not None and col in d.columns and d[col].isnull().sum() == 0


def cols(ns, *names, frame="df"):
    d = ns.get(frame)
    return d is not None and all(c in d.columns for c in names)


def rows(ns, n, frame="df"):
    d = ns.get(frame)
    return d is not None and len(d) == n


Q = lambda no, score, domain, text, answer, check, why, data=None: {
    "no": no, "score": score, "domain": domain, "text": text,
    "answer": answer, "check": check, "why": why, "data": data,
}

A, P, M = "데이터 분석", "데이터 전처리", "AI 모델링"

QUESTIONS = [
    # ══ 세트 1 (1~5) 데이터 분석 — 불러오기와 첫인상 ══════════════════════
    Q(1, 5, A, "pandas 라이브러리를 pd라는 별칭으로 불러오시오.",
      "import pandas as pd",
      lambda ns: ns.get("pd") is not None,
      "pandas를 pd로 불러와야 이후 모든 문제에서 pd.____ 를 쓸 수 있습니다."),
    Q(2, 5, A, "customers.csv 파일을 읽어 df에 저장하시오.",
      'df = pd.read_csv("customers.csv")',
      lambda ns: has(ns, "df", "shape"),
      "read_csv가 CSV를 표(DataFrame)로 읽습니다. df라는 이름표에 담아둡니다.", "customers.csv"),
    Q(3, 5, A, "df의 상위 5개 행을 출력하시오.",
      "df.head()",
      lambda ns: has(ns, "df", "shape"),
      "head()는 위에서 5줄만 보여줍니다. 괄호 안에 숫자를 넣으면 그 개수만큼 나옵니다.", "customers.csv"),
    Q(4, 5, A, "df의 행 개수와 열 개수를 확인하시오.",
      "df.shape",
      lambda ns: has(ns, "df", "shape"),
      "shape는 (행, 열)을 알려줍니다. 데이터를 받으면 가장 먼저 하는 확인입니다.", "customers.csv"),
    Q(5, 5, A, "df의 컬럼별 자료형과 결측치 현황을 한 번에 확인하시오.",
      "df.info()",
      lambda ns: has(ns, "df", "shape"),
      "info()는 자료형·비어있지 않은 개수·메모리를 한 번에 보여줍니다.", "customers.csv"),

    # ══ 세트 2 (6~10) 데이터 분석 — 기술통계와 결측 ═══════════════════════
    Q(6, 5, A, "df의 수치형 컬럼에 대한 기술통계(평균, 표준편차 등)를 출력하시오.",
      "df.describe()",
      lambda ns: has(ns, "df", "shape"),
      "describe()는 count·mean·std·min·사분위수·max를 한 번에 줍니다.", "customers.csv"),
    Q(7, 5, A, "각 컬럼의 결측치 개수를 확인하시오.",
      "df.isnull().sum()",
      lambda ns: has(ns, "df", "shape"),
      "isnull()이 빈칸을 True로 바꾸고, sum()이 True 개수를 셉니다.", "customers.csv"),
    Q(8, 5, A, "df의 컬럼 이름만 모두 출력하시오.",
      "df.columns",
      lambda ns: has(ns, "df", "shape"),
      "columns는 컬럼 이름 목록입니다. 오타로 KeyError가 날 때 먼저 확인하는 곳입니다.", "customers.csv"),
    Q(9, 5, A, "region 컬럼의 값별 개수를 세시오.",
      'df["region"].value_counts()',
      lambda ns: has(ns, "df", "shape"),
      "value_counts()는 범주형 컬럼의 값이 각각 몇 번 나오는지 셉니다.", "customers.csv"),
    Q(10, 5, A, "df에 중복된 행이 몇 개 있는지 확인하시오.",
      "df.duplicated().sum()",
      lambda ns: has(ns, "df", "shape"),
      "duplicated()가 중복행을 True로 표시하고 sum()이 셉니다. 품질 점검의 기본입니다.", "customers.csv"),

    # ══ 세트 3 (11~15) 데이터 분석 — 선택과 필터 ══════════════════════════
    Q(11, 5, A, "df에서 age 컬럼만 선택해 출력하시오.",
      'df["age"]',
      lambda ns: has(ns, "df", "shape"),
      "컬럼 하나는 대괄호에 이름을 넣어 꺼냅니다. 결과는 Series입니다.", "customers.csv"),
    Q(12, 5, A, "df에서 age와 monthly_spend 두 컬럼만 선택해 출력하시오.",
      'df[["age", "monthly_spend"]]',
      lambda ns: has(ns, "df", "shape"),
      "컬럼 여러 개는 대괄호를 두 번 씁니다. 안쪽은 컬럼 이름 리스트입니다.", "customers.csv"),
    Q(13, 5, A, "age가 40 이상인 행만 골라 adult에 저장하시오.",
      'adult = df[df["age"] >= 40]',
      lambda ns: has(ns, "adult", "shape") and (ns["adult"]["age"] >= 40).all(),
      "df[조건] 형태로 행을 거릅니다. 조건은 True/False가 담긴 Series입니다.", "customers.csv"),
    Q(14, 5, A, "region이 'Seoul'인 행의 개수를 구하시오.",
      'len(df[df["region"] == "Seoul"])',
      lambda ns: has(ns, "df", "shape"),
      "문자열 비교는 == 를 씁니다. len()으로 걸러진 행 수를 셉니다.", "customers.csv"),
    Q(15, 5, A, "df를 monthly_spend 기준 내림차순으로 정렬해 출력하시오.",
      'df.sort_values("monthly_spend", ascending=False)',
      lambda ns: has(ns, "df", "shape"),
      "sort_values로 정렬합니다. ascending=False면 큰 값이 위로 옵니다.", "customers.csv"),

    # ══ 세트 4 (16~20) 데이터 분석 — 집계 ═════════════════════════════════
    Q(16, 5, A, "sales.csv를 읽어 df에 저장하시오.",
      'df = pd.read_csv("sales.csv")',
      lambda ns: has(ns, "df", "shape") and "store" in ns["df"].columns,
      "문제마다 사용하는 파일이 다릅니다. 지시문의 파일명을 정확히 보세요.", "sales.csv"),
    Q(17, 5, A, "store별 amount 합계를 구하시오.",
      'df.groupby("store")["amount"].sum()',
      lambda ns: has(ns, "df", "shape"),
      "groupby(기준)[대상].집계함수() 가 집계의 기본 문형입니다.", "sales.csv"),
    Q(18, 5, A, "category별 amount 평균을 구하시오.",
      'df.groupby("category")["amount"].mean()',
      lambda ns: has(ns, "df", "shape"),
      "sum 대신 mean을 쓰면 평균입니다. max, min, count도 같은 자리에 들어갑니다.", "sales.csv"),
    Q(19, 5, A, "store별 amount 합계를 큰 순서로 정렬하시오.",
      'df.groupby("store")["amount"].sum().sort_values(ascending=False)',
      lambda ns: has(ns, "df", "shape"),
      "집계 결과에 바로 sort_values를 이어붙일 수 있습니다. 이걸 체이닝이라 합니다.", "sales.csv"),
    Q(20, 5, A, "amount 컬럼의 전체 합계를 구하시오.",
      'df["amount"].sum()',
      lambda ns: has(ns, "df", "shape"),
      "컬럼 하나를 꺼내 sum()하면 전체 합입니다.", "sales.csv"),

    # ══ 세트 5 (21~25) 데이터 분석 — 종합 ═════════════════════════════════
    Q(21, 5, A, "customers.csv를 읽어 df에 저장하고 행·열 개수를 확인하시오.",
      'df = pd.read_csv("customers.csv")\ndf.shape',
      lambda ns: has(ns, "df", "shape") and "churn" in ns["df"].columns,
      "읽기와 확인을 한 셀에서 이어서 합니다. 마지막 줄의 값이 자동 출력됩니다.", "customers.csv"),
    Q(22, 5, A, "churn 컬럼의 값별 개수를 세어 클래스 균형을 확인하시오.",
      'df["churn"].value_counts()',
      lambda ns: has(ns, "df", "shape"),
      "목표변수의 균형 확인은 모델링 전 필수입니다. 한쪽이 너무 적으면 대책이 필요합니다.", "customers.csv"),
    Q(23, 5, A, "age 컬럼의 평균값을 구하시오.",
      'df["age"].mean()',
      lambda ns: has(ns, "df", "shape"),
      "mean()은 결측치를 자동으로 빼고 계산합니다.", "customers.csv"),
    Q(24, 5, A, "grade별 monthly_spend 평균을 구하시오.",
      'df.groupby("grade")["monthly_spend"].mean()',
      lambda ns: has(ns, "df", "shape"),
      "범주별 차이를 보는 건 특성 이해의 기본입니다.", "customers.csv"),
    Q(25, 5, A, "age와 monthly_spend의 상관계수를 구하시오.",
      'df[["age", "monthly_spend"]].corr()',
      lambda ns: has(ns, "df", "shape"),
      "corr()은 -1~1 사이 상관계수를 줍니다. 1에 가까울수록 같이 커집니다.", "customers.csv"),

    # ══ 세트 6 (26~30) 전처리 — 결측치 ════════════════════════════════════
    Q(26, 5, P, "customers.csv를 읽어 df에 저장하시오.",
      'df = pd.read_csv("customers.csv")',
      lambda ns: has(ns, "df", "shape") and "churn" in ns["df"].columns,
      "전처리 문제도 항상 데이터를 먼저 읽는 것에서 시작합니다.", "customers.csv"),
    Q(27, 6, P, "age 컬럼의 결측치를 age의 평균값으로 채우시오.",
      'df["age"] = df["age"].fillna(df["age"].mean())',
      lambda ns: nomiss(ns, "age"),
      "fillna로 채운 결과를 다시 df['age']에 넣어야 실제로 반영됩니다.", "customers.csv"),
    Q(28, 6, P, "monthly_spend의 결측치를 중앙값으로 채우시오.",
      'df["monthly_spend"] = df["monthly_spend"].fillna(df["monthly_spend"].median())',
      lambda ns: nomiss(ns, "monthly_spend"),
      "이상치가 있으면 평균보다 중앙값(median)이 안전합니다.", "customers.csv"),
    Q(29, 6, P, "region의 결측치를 최빈값으로 채우시오.",
      'df["region"] = df["region"].fillna(df["region"].mode()[0])',
      lambda ns: nomiss(ns, "region"),
      "문자열은 평균이 없으므로 최빈값(mode)을 씁니다. mode()는 여러 개일 수 있어 [0]을 붙입니다.", "customers.csv"),
    Q(30, 7, P, "satisfaction의 결측치가 있는 행을 삭제하시오.",
      'df = df.dropna(subset=["satisfaction"])',
      lambda ns: nomiss(ns, "satisfaction"),
      "dropna(subset=[컬럼])은 그 컬럼이 빈 행만 지웁니다. 결과를 df에 다시 담아야 합니다.", "customers.csv"),

    # ══ 세트 7 (31~35) 전처리 — 중복·이상치 ══════════════════════════════
    Q(31, 5, P, "customers.csv를 읽어 df에 저장하고 중복행 개수를 확인하시오.",
      'df = pd.read_csv("customers.csv")\ndf.duplicated().sum()',
      lambda ns: has(ns, "df", "shape"),
      "중복은 모델을 왜곡시키므로 초반에 확인합니다.", "customers.csv"),
    Q(32, 6, P, "df에서 중복된 행을 제거하시오.",
      "df = df.drop_duplicates()",
      lambda ns: has(ns, "df", "shape") and ns["df"].duplicated().sum() == 0,
      "drop_duplicates()는 완전히 같은 행을 하나만 남깁니다.", "customers.csv"),
    Q(33, 6, P, "monthly_spend의 1사분위수(Q1)와 3사분위수(Q3)를 구해 각각 q1, q3에 저장하시오.",
      'q1 = df["monthly_spend"].quantile(0.25)\nq3 = df["monthly_spend"].quantile(0.75)',
      lambda ns: ns.get("q1") is not None and ns.get("q3") is not None and ns["q3"] > ns["q1"],
      "quantile(0.25)가 Q1입니다. IQR 이상치 판별의 재료입니다.", "customers.csv"),
    Q(34, 7, P, "IQR을 구해 iqr에 저장하시오. (IQR = Q3 - Q1, 앞 문제의 q1·q3 사용)",
      "iqr = q3 - q1",
      lambda ns: ns.get("iqr") is not None and ns["iqr"] > 0,
      "IQR은 가운데 50%의 폭입니다. 이 폭의 1.5배를 벗어나면 보통 이상치로 봅니다.", "customers.csv"),
    Q(35, 6, P, "monthly_spend가 Q3 + 1.5*IQR 보다 큰 행의 개수를 구하시오.",
      'len(df[df["monthly_spend"] > q3 + 1.5 * iqr])',
      lambda ns: ns.get("iqr") is not None,
      "이게 표준적인 이상치 판별 기준입니다. 지우기 전에 개수부터 확인합니다.", "customers.csv"),

    # ══ 세트 8 (36~40) 전처리 — 인코딩 ════════════════════════════════════
    Q(36, 5, P, "customers.csv를 읽어 df에 저장하시오.",
      'df = pd.read_csv("customers.csv")',
      lambda ns: has(ns, "df", "shape") and "grade" in ns["df"].columns,
      "인코딩 문제도 데이터 읽기부터 시작합니다.", "customers.csv"),
    Q(37, 6, P, "region 컬럼을 원핫 인코딩하여 df에 반영하시오.",
      'df = pd.get_dummies(df, columns=["region"])',
      lambda ns: has(ns, "df", "shape") and any(c.startswith("region_") for c in ns["df"].columns),
      "get_dummies는 범주마다 0/1 컬럼을 새로 만듭니다. 순서가 없는 범주에 씁니다.", "customers.csv"),
    Q(38, 7, P, "grade 컬럼을 bronze=0, silver=1, gold=2로 바꾸어 df['grade']에 반영하시오.",
      'df["grade"] = df["grade"].map({"bronze": 0, "silver": 1, "gold": 2})',
      lambda ns: cols(ns, "grade") and str(ns["df"]["grade"].dtype) != "object",
      "순서가 있는 범주(등급)는 map으로 숫자를 지정합니다. 이게 라벨/순서 인코딩입니다.", "customers.csv"),
    Q(39, 6, P, "sklearn의 LabelEncoder를 불러오시오.",
      "from sklearn.preprocessing import LabelEncoder",
      lambda ns: ns.get("LabelEncoder") is not None,
      "sklearn은 from ... import ... 형태로 필요한 것만 꺼내 씁니다.", "customers.csv"),
    Q(40, 6, P, "customer_id 컬럼을 삭제하시오. (모델 학습에 쓸모없는 식별자)",
      'df = df.drop(columns=["customer_id"])',
      lambda ns: has(ns, "df", "shape") and "customer_id" not in ns["df"].columns,
      "ID처럼 의미 없는 컬럼은 학습 전에 버립니다. 남기면 과적합의 원인이 됩니다.", "customers.csv"),

    # ══ 세트 9 (41~45) 전처리 — 스케일링 ══════════════════════════════════
    Q(41, 5, P, "sklearn에서 StandardScaler를 불러오시오.",
      "from sklearn.preprocessing import StandardScaler",
      lambda ns: ns.get("StandardScaler") is not None,
      "StandardScaler는 평균 0, 표준편차 1로 맞춥니다.", "customers.csv"),
    Q(42, 6, P, "houses.csv를 읽어 df에 저장하시오.",
      'df = pd.read_csv("houses.csv")',
      lambda ns: has(ns, "df", "shape") and "price" in ns["df"].columns,
      "회귀 연습용 데이터입니다. price가 목표변수입니다.", "houses.csv"),
    Q(43, 7, P, "area 컬럼의 결측치를 평균으로 채우시오.",
      'df["area"] = df["area"].fillna(df["area"].mean())',
      lambda ns: nomiss(ns, "area"),
      "스케일링 전에 결측치를 먼저 없애야 합니다. 빈칸이 있으면 스케일러가 오류를 냅니다.", "houses.csv"),
    Q(44, 6, P, "distance_station의 결측치를 중앙값으로 채우시오.",
      'df["distance_station"] = df["distance_station"].fillna(df["distance_station"].median())',
      lambda ns: nomiss(ns, "distance_station"),
      "치우친 분포에는 중앙값이 안전합니다.", "houses.csv"),
    Q(45, 6, P, "MinMaxScaler를 불러와 scaler라는 이름으로 만드시오.",
      "from sklearn.preprocessing import MinMaxScaler\nscaler = MinMaxScaler()",
      lambda ns: ns.get("scaler") is not None and hasattr(ns["scaler"], "fit_transform"),
      "MinMaxScaler는 0~1 범위로 압축합니다. 만들기(생성)와 적용(fit)은 다른 단계입니다.", "houses.csv"),

    # ══ 세트 10 (46~50) 전처리 — 분리 ═════════════════════════════════════
    Q(46, 5, P, "customers.csv를 읽어 df에 저장하고 customer_id를 삭제하시오.",
      'df = pd.read_csv("customers.csv")\ndf = df.drop(columns=["customer_id"])',
      lambda ns: has(ns, "df", "shape") and "customer_id" not in ns["df"].columns,
      "모델링 준비의 첫 단계입니다.", "customers.csv"),
    Q(47, 6, P, "결측치가 있는 행을 모두 삭제하시오.",
      "df = df.dropna()",
      lambda ns: has(ns, "df", "shape") and ns["df"].isnull().sum().sum() == 0,
      "인자 없는 dropna()는 빈칸이 하나라도 있는 행을 전부 지웁니다.", "customers.csv"),
    Q(48, 6, P, "region과 grade를 원핫 인코딩하시오.",
      'df = pd.get_dummies(df, columns=["region", "grade"])',
      lambda ns: has(ns, "df", "shape") and any(c.startswith("region_") for c in ns["df"].columns),
      "columns에 여러 개를 한 번에 넘길 수 있습니다.", "customers.csv"),
    Q(49, 7, P, "churn을 목표변수 y로, 나머지 전부를 X로 분리하시오.",
      'X = df.drop(columns=["churn"])\ny = df["churn"]',
      lambda ns: has(ns, "X", "shape") and ns.get("y") is not None and "churn" not in ns["X"].columns,
      "X는 문제, y는 정답입니다. y를 X에 남기면 답을 보고 푸는 셈이 됩니다.", "customers.csv"),
    Q(50, 6, P, "train_test_split을 불러오시오.",
      "from sklearn.model_selection import train_test_split",
      lambda ns: ns.get("train_test_split") is not None,
      "모델 성능을 정직하게 재려면 학습용과 검증용을 나눠야 합니다.", "customers.csv"),

    # ══ 세트 11 (51~55) 전처리 — 분할 마무리 ═════════════════════════════
    Q(51, 5, P, "customers.csv를 읽고 customer_id 삭제 후 결측행을 제거하시오.",
      'df = pd.read_csv("customers.csv")\ndf = df.drop(columns=["customer_id"]).dropna()',
      lambda ns: has(ns, "df", "shape") and ns["df"].isnull().sum().sum() == 0,
      "점을 이어 붙이면 한 줄로 여러 처리를 할 수 있습니다.", "customers.csv"),
    Q(52, 6, P, "region과 grade를 원핫 인코딩하고 X, y를 만드시오. (목표: churn)",
      'df = pd.get_dummies(df, columns=["region", "grade"])\nX = df.drop(columns=["churn"])\ny = df["churn"]',
      lambda ns: has(ns, "X", "shape") and ns.get("y") is not None,
      "모델에 넣기 직전 상태입니다. X에는 숫자만 남아야 합니다.", "customers.csv"),
    Q(53, 7, P, "X, y를 8:2로 나누어 X_train, X_test, y_train, y_test를 만드시오. (random_state=42)",
      "from sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)",
      lambda ns: all(ns.get(k) is not None for k in ["X_train", "X_test", "y_train", "y_test"]),
      "test_size=0.2가 검증용 20%입니다. random_state를 고정해야 매번 같은 결과가 나옵니다.", "customers.csv"),
    Q(54, 6, P, "X_train과 X_test의 행 개수를 각각 확인하시오.",
      "X_train.shape, X_test.shape",
      lambda ns: ns.get("X_train") is not None,
      "8:2로 잘 나뉘었는지 확인하는 습관을 들이세요.", "customers.csv"),
    Q(55, 6, P, "StandardScaler로 X_train을 학습·변환하여 X_train_scaled에 저장하시오.",
      "from sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)",
      lambda ns: ns.get("X_train_scaled") is not None,
      "fit은 학습 데이터에만 합니다. 검증 데이터에 fit하면 정보가 새어나갑니다(데이터 누수).", "customers.csv"),

    # ══ 세트 12 (56~60) 모델링 — 분류 시작 ═══════════════════════════════
    Q(56, 6, M, "customers.csv를 읽고 전처리하여 X, y를 만드시오. (customer_id 삭제, 결측행 제거, region·grade 원핫, 목표 churn)",
      'df = pd.read_csv("customers.csv").drop(columns=["customer_id"]).dropna()\ndf = pd.get_dummies(df, columns=["region", "grade"])\nX = df.drop(columns=["churn"])\ny = df["churn"]',
      lambda ns: has(ns, "X", "shape") and ns.get("y") is not None,
      "모델링 문제는 이 준비가 반복됩니다. 손에 익혀두면 시간을 크게 아낍니다.", "customers.csv"),
    Q(57, 8, M, "X, y를 8:2로 분할하시오. (random_state=42)",
      "from sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)",
      lambda ns: all(ns.get(k) is not None for k in ["X_train", "X_test", "y_train", "y_test"]),
      "분할 없이 학습하면 성능을 정직하게 잴 수 없습니다.", "customers.csv"),
    Q(58, 8, M, "로지스틱 회귀 모델을 불러와 model이라는 이름으로 만드시오. (max_iter=1000)",
      "from sklearn.linear_model import LogisticRegression\nmodel = LogisticRegression(max_iter=1000)",
      lambda ns: ns.get("model") is not None and hasattr(ns["model"], "fit"),
      "이름은 회귀지만 분류 모델입니다. max_iter를 늘리면 수렴 경고가 줄어듭니다.", "customers.csv"),
    Q(59, 9, M, "model을 X_train, y_train으로 학습시키시오.",
      "model.fit(X_train, y_train)",
      lambda ns: ns.get("model") is not None and hasattr(ns["model"], "classes_"),
      "fit이 실제 학습입니다. 이 한 줄이 모델링의 핵심입니다.", "customers.csv"),
    Q(60, 9, M, "X_test에 대한 예측값을 구해 pred에 저장하시오.",
      "pred = model.predict(X_test)",
      lambda ns: ns.get("pred") is not None,
      "predict는 학습된 모델로 답을 맞혀보는 단계입니다.", "customers.csv"),

    # ══ 세트 13 (61~65) 모델링 — 평가 ════════════════════════════════════
    Q(61, 6, M, "customers.csv로 X, y를 만들고 8:2 분할하시오. (random_state=42)",
      'df = pd.read_csv("customers.csv").drop(columns=["customer_id"]).dropna()\ndf = pd.get_dummies(df, columns=["region", "grade"])\nX = df.drop(columns=["churn"])\ny = df["churn"]\nfrom sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)',
      lambda ns: ns.get("X_train") is not None,
      "평가 문제도 데이터 준비부터입니다.", "customers.csv"),
    Q(62, 8, M, "랜덤포레스트 분류 모델을 만들어 학습시키시오. (random_state=42)",
      "from sklearn.ensemble import RandomForestClassifier\nmodel = RandomForestClassifier(random_state=42)\nmodel.fit(X_train, y_train)",
      lambda ns: ns.get("model") is not None and hasattr(ns["model"], "classes_"),
      "랜덤포레스트는 결정트리 여러 개의 다수결입니다. 시험 단골입니다.", "customers.csv"),
    Q(63, 9, M, "accuracy_score를 불러와 X_test에 대한 정확도를 출력하시오.",
      "from sklearn.metrics import accuracy_score\npred = model.predict(X_test)\naccuracy_score(y_test, pred)",
      lambda ns: ns.get("pred") is not None,
      "accuracy_score(정답, 예측) 순서입니다. 순서를 바꿔도 값은 같지만 습관을 들이세요.", "customers.csv"),
    Q(64, 9, M, "혼동행렬(confusion matrix)을 출력하시오.",
      "from sklearn.metrics import confusion_matrix\nconfusion_matrix(y_test, pred)",
      lambda ns: ns.get("pred") is not None,
      "정확도 하나로는 부족합니다. 어떤 걸 틀렸는지 봐야 합니다.", "customers.csv"),
    Q(65, 8, M, "precision, recall, f1을 한 번에 보여주는 리포트를 출력하시오.",
      "from sklearn.metrics import classification_report\nprint(classification_report(y_test, pred))",
      lambda ns: ns.get("pred") is not None,
      "classification_report는 주요 지표를 한 표로 줍니다. print로 감싸야 예쁘게 나옵니다.", "customers.csv"),

    # ══ 세트 14 (66~70) 모델링 — 회귀 ════════════════════════════════════
    Q(66, 6, M, "houses.csv를 읽어 결측행을 제거하고 df에 저장하시오.",
      'df = pd.read_csv("houses.csv").dropna()',
      lambda ns: has(ns, "df", "shape") and ns["df"].isnull().sum().sum() == 0,
      "회귀 문제입니다. 목표변수 price는 연속값입니다.", "houses.csv"),
    Q(67, 8, M, "price를 y로, 나머지를 X로 분리한 뒤 8:2 분할하시오. (random_state=42)",
      'X = df.drop(columns=["price"])\ny = df["price"]\nfrom sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)',
      lambda ns: ns.get("X_train") is not None,
      "분류든 회귀든 X·y 분리와 분할 절차는 똑같습니다.", "houses.csv"),
    Q(68, 9, M, "선형회귀 모델을 만들어 학습시키시오.",
      "from sklearn.linear_model import LinearRegression\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)",
      lambda ns: ns.get("model") is not None and hasattr(ns["model"], "coef_"),
      "연속값 예측에는 Classifier가 아니라 Regressor를 씁니다.", "houses.csv"),
    Q(69, 9, M, "X_test를 예측해 pred에 저장하고 R² 점수를 출력하시오.",
      "from sklearn.metrics import r2_score\npred = model.predict(X_test)\nr2_score(y_test, pred)",
      lambda ns: ns.get("pred") is not None,
      "R²는 1에 가까울수록 좋습니다. 회귀의 대표 지표입니다.", "houses.csv"),
    Q(70, 8, M, "MAE(평균절대오차)를 구하시오.",
      "from sklearn.metrics import mean_absolute_error\nmean_absolute_error(y_test, pred)",
      lambda ns: ns.get("pred") is not None,
      "MAE는 평균적으로 얼마나 빗나갔는지를 원래 단위로 알려줍니다.", "houses.csv"),

    # ══ 세트 15 (71~75) 모델링 — 여러 모델 비교 ══════════════════════════
    Q(71, 6, M, "customers.csv로 X_train, X_test, y_train, y_test를 준비하시오. (random_state=42)",
      'df = pd.read_csv("customers.csv").drop(columns=["customer_id"]).dropna()\ndf = pd.get_dummies(df, columns=["region", "grade"])\nX = df.drop(columns=["churn"])\ny = df["churn"]\nfrom sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)',
      lambda ns: ns.get("X_train") is not None,
      "여러 모델을 비교하려면 같은 데이터로 재야 공정합니다.", "customers.csv"),
    Q(72, 8, M, "결정트리 분류 모델을 만들어 학습시키시오. (random_state=42)",
      "from sklearn.tree import DecisionTreeClassifier\nmodel = DecisionTreeClassifier(random_state=42)\nmodel.fit(X_train, y_train)",
      lambda ns: ns.get("model") is not None and hasattr(ns["model"], "classes_"),
      "결정트리는 규칙을 사람이 읽을 수 있다는 장점이 있습니다.", "customers.csv"),
    Q(73, 9, M, "KNN 분류 모델을 만들어 학습시키시오. (n_neighbors=5)",
      "from sklearn.neighbors import KNeighborsClassifier\nmodel = KNeighborsClassifier(n_neighbors=5)\nmodel.fit(X_train, y_train)",
      lambda ns: ns.get("model") is not None and hasattr(ns["model"], "classes_"),
      "KNN은 가까운 이웃 k개의 다수결로 정합니다. 스케일링이 중요합니다.", "customers.csv"),
    Q(74, 9, M, "랜덤포레스트를 학습시키고 특성 중요도를 출력하시오. (random_state=42)",
      "from sklearn.ensemble import RandomForestClassifier\nmodel = RandomForestClassifier(random_state=42)\nmodel.fit(X_train, y_train)\nmodel.feature_importances_",
      lambda ns: ns.get("model") is not None and hasattr(ns["model"], "feature_importances_"),
      "중요도는 예측에 기여한 정도일 뿐, 인과관계가 아닙니다.", "customers.csv"),
    Q(75, 8, M, "학습 데이터에 대한 정확도를 출력하시오. (과적합 확인)",
      "model.score(X_train, y_train)",
      lambda ns: ns.get("model") is not None,
      "학습 점수만 높고 검증 점수가 낮으면 과적합입니다.", "customers.csv"),

    # ══ 세트 16 (76~80) 모델링 — 개선 ════════════════════════════════════
    Q(76, 6, M, "customers.csv로 X_train, X_test, y_train, y_test를 준비하시오. (random_state=42)",
      'df = pd.read_csv("customers.csv").drop(columns=["customer_id"]).dropna()\ndf = pd.get_dummies(df, columns=["region", "grade"])\nX = df.drop(columns=["churn"])\ny = df["churn"]\nfrom sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)',
      lambda ns: ns.get("X_train") is not None,
      "성능 개선 문제도 같은 준비에서 출발합니다.", "customers.csv"),
    Q(77, 8, M, "랜덤포레스트를 n_estimators=200으로 만들어 학습시키시오. (random_state=42)",
      "from sklearn.ensemble import RandomForestClassifier\nmodel = RandomForestClassifier(n_estimators=200, random_state=42)\nmodel.fit(X_train, y_train)",
      lambda ns: ns.get("model") is not None and hasattr(ns["model"], "classes_"),
      "n_estimators는 나무 개수입니다. 늘리면 보통 안정되지만 느려집니다.", "customers.csv"),
    Q(78, 9, M, "max_depth=5로 제한한 랜덤포레스트를 학습시키시오. (random_state=42)",
      "model = RandomForestClassifier(max_depth=5, random_state=42)\nmodel.fit(X_train, y_train)",
      lambda ns: ns.get("model") is not None and hasattr(ns["model"], "classes_"),
      "깊이를 제한하면 과적합이 줄어듭니다. 대표적인 규제 방법입니다.", "customers.csv"),
    Q(79, 9, M, "cross_val_score로 5-fold 교차검증 점수를 구하시오.",
      "from sklearn.model_selection import cross_val_score\ncross_val_score(model, X_train, y_train, cv=5)",
      lambda ns: ns.get("model") is not None,
      "한 번 나눈 결과는 운에 좌우됩니다. 교차검증이 더 믿을 만합니다.", "customers.csv"),
    Q(80, 8, M, "교차검증 점수의 평균을 구하시오.",
      "from sklearn.model_selection import cross_val_score\ncross_val_score(model, X_train, y_train, cv=5).mean()",
      lambda ns: ns.get("model") is not None,
      "평균으로 보고합니다. 편차가 크면 불안정한 모델입니다.", "customers.csv"),

    # ══ 세트 17 (81~85) 모델링 — 딥러닝 개념 ═════════════════════════════
    Q(81, 6, M, "customers.csv로 X_train, X_test, y_train, y_test를 준비하시오. (random_state=42)",
      'df = pd.read_csv("customers.csv").drop(columns=["customer_id"]).dropna()\ndf = pd.get_dummies(df, columns=["region", "grade"])\nX = df.drop(columns=["churn"])\ny = df["churn"]\nfrom sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)',
      lambda ns: ns.get("X_train") is not None,
      "딥러닝도 데이터 준비는 동일합니다.", "customers.csv"),
    Q(82, 8, M, "X_train을 StandardScaler로 변환해 X_train_s에 저장하시오.",
      "from sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\nX_train_s = scaler.fit_transform(X_train)",
      lambda ns: ns.get("X_train_s") is not None,
      "신경망은 스케일에 민감합니다. 표준화가 사실상 필수입니다.", "customers.csv"),
    Q(83, 9, M, "X_test를 같은 scaler로 변환해 X_test_s에 저장하시오. (fit 하지 말 것)",
      "X_test_s = scaler.transform(X_test)",
      lambda ns: ns.get("X_test_s") is not None,
      "검증 데이터에는 transform만 씁니다. fit하면 데이터 누수입니다. 시험 단골 함정입니다.", "customers.csv"),
    Q(84, 9, M, "MLPClassifier(신경망)를 불러와 학습시키시오. (max_iter=500, random_state=42)",
      "from sklearn.neural_network import MLPClassifier\nmodel = MLPClassifier(max_iter=500, random_state=42)\nmodel.fit(X_train_s, y_train)",
      lambda ns: ns.get("model") is not None and hasattr(ns["model"], "classes_"),
      "MLP는 Dense 층을 쌓은 기본 신경망입니다. 스케일된 데이터를 넣습니다.", "customers.csv"),
    Q(85, 8, M, "신경망 모델의 검증 정확도를 출력하시오.",
      "model.score(X_test_s, y_test)",
      lambda ns: ns.get("model") is not None,
      "score는 predict와 accuracy_score를 한 번에 해줍니다.", "customers.csv"),

    # ══ 세트 18 (86~90) 실전 혼합 ═════════════════════════════════════════
    Q(86, 6, A, "sales.csv를 읽어 df에 저장하고 결측치를 확인하시오.",
      'df = pd.read_csv("sales.csv")\ndf.isnull().sum()',
      lambda ns: has(ns, "df", "shape") and "store" in ns["df"].columns,
      "실전에서는 읽자마자 상태를 확인합니다.", "sales.csv"),
    Q(87, 7, P, "quantity의 결측치를 중앙값으로 채우시오.",
      'df["quantity"] = df["quantity"].fillna(df["quantity"].median())',
      lambda ns: nomiss(ns, "quantity"),
      "수량은 정수형이므로 중앙값이 자연스럽습니다.", "sales.csv"),
    Q(88, 7, A, "store별 amount 합계를 구해 가장 매출이 큰 매장을 확인하시오.",
      'df.groupby("store")["amount"].sum().sort_values(ascending=False)',
      lambda ns: has(ns, "df", "shape"),
      "집계 후 정렬은 실무·시험 모두에서 가장 자주 쓰는 조합입니다.", "sales.csv"),
    Q(89, 7, A, "category별 quantity 평균을 구하시오.",
      'df.groupby("category")["quantity"].mean()',
      lambda ns: has(ns, "df", "shape"),
      "groupby 문형은 대상과 함수만 바꿔가며 반복됩니다.", "sales.csv"),
    Q(90, 8, P, "store 컬럼을 원핫 인코딩하시오.",
      'df = pd.get_dummies(df, columns=["store"])',
      lambda ns: has(ns, "df", "shape") and any(c.startswith("store_") for c in ns["df"].columns),
      "매장명처럼 순서 없는 범주는 원핫이 맞습니다.", "sales.csv"),

    # ══ 세트 19 (91~95) 실전 혼합 ═════════════════════════════════════════
    Q(91, 6, A, "houses.csv를 읽어 df에 저장하고 기술통계를 확인하시오.",
      'df = pd.read_csv("houses.csv")\ndf.describe()',
      lambda ns: has(ns, "df", "shape") and "price" in ns["df"].columns,
      "describe()로 이상한 최솟값·최댓값이 없는지 훑습니다.", "houses.csv"),
    Q(92, 7, P, "area와 distance_station의 결측치를 각각 평균으로 채우시오.",
      'df["area"] = df["area"].fillna(df["area"].mean())\ndf["distance_station"] = df["distance_station"].fillna(df["distance_station"].mean())',
      lambda ns: nomiss(ns, "area") and nomiss(ns, "distance_station"),
      "여러 컬럼을 처리할 때는 한 줄씩 확실하게 씁니다.", "houses.csv"),
    Q(93, 8, A, "price와 다른 컬럼들의 상관계수를 구하시오.",
      'df.corr()["price"]',
      lambda ns: has(ns, "df", "shape"),
      "목표변수와 상관이 높은 특성을 먼저 살펴봅니다.", "houses.csv"),
    Q(94, 9, M, "price를 y로 분리하고 랜덤포레스트 회귀 모델을 학습시키시오. (random_state=42, 8:2 분할)",
      'X = df.drop(columns=["price"])\ny = df["price"]\nfrom sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\nfrom sklearn.ensemble import RandomForestRegressor\nmodel = RandomForestRegressor(random_state=42)\nmodel.fit(X_train, y_train)',
      lambda ns: ns.get("model") is not None and hasattr(ns["model"], "feature_importances_"),
      "회귀에는 Regressor를 씁니다. Classifier를 쓰면 오류가 납니다.", "houses.csv"),
    Q(95, 9, M, "검증 데이터의 R² 점수를 출력하시오.",
      "model.score(X_test, y_test)",
      lambda ns: ns.get("model") is not None,
      "회귀 모델의 score는 R²를 돌려줍니다.", "houses.csv"),

    # ══ 세트 20 (96~100) 실전 종합 ════════════════════════════════════════
    Q(96, 6, A, "customers.csv를 읽어 df에 저장하고 churn 비율을 확인하시오.",
      'df = pd.read_csv("customers.csv")\ndf["churn"].value_counts()',
      lambda ns: has(ns, "df", "shape") and "churn" in ns["df"].columns,
      "목표변수 분포 확인은 모델링 전 필수 절차입니다.", "customers.csv"),
    Q(97, 7, P, "customer_id를 삭제하고 결측행을 제거하시오.",
      'df = df.drop(columns=["customer_id"]).dropna()',
      lambda ns: has(ns, "df", "shape") and "customer_id" not in ns["df"].columns and ns["df"].isnull().sum().sum() == 0,
      "식별자 제거와 결측 처리는 거의 항상 함께 나옵니다.", "customers.csv"),
    Q(98, 8, P, "region과 grade를 원핫 인코딩한 뒤 X, y를 만들고 8:2로 분할하시오. (random_state=42)",
      'df = pd.get_dummies(df, columns=["region", "grade"])\nX = df.drop(columns=["churn"])\ny = df["churn"]\nfrom sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)',
      lambda ns: ns.get("X_train") is not None,
      "여기까지가 전처리의 끝이자 모델링의 시작점입니다.", "customers.csv"),
    Q(99, 10, M, "랜덤포레스트로 학습하고 검증 정확도를 출력하시오. (random_state=42)",
      "from sklearn.ensemble import RandomForestClassifier\nmodel = RandomForestClassifier(random_state=42)\nmodel.fit(X_train, y_train)\nmodel.score(X_test, y_test)",
      lambda ns: ns.get("model") is not None and hasattr(ns["model"], "classes_"),
      "14문항 시험의 마지막은 대개 이런 형태입니다.", "customers.csv"),
    Q(100, 9, M, "classification_report로 최종 성능을 출력하시오.",
      "from sklearn.metrics import classification_report\npred = model.predict(X_test)\nprint(classification_report(y_test, pred))",
      lambda ns: ns.get("pred") is not None,
      "정확도 한 숫자보다 지표 전체를 보고 판단하는 습관이 실전에서 점수를 지킵니다.", "customers.csv"),
]


SETS = [(i, QUESTIONS[i * 5:(i + 1) * 5]) for i in range(20)]

# 세트별 사전 준비 코드. 문제를 풀기 전에 조용히 실행됩니다.
# 실제 시험에서도 앞 문항의 결과가 남아 있는 상태로 이어서 풀기 때문에,
# 세트를 중간부터 열어도 같은 조건이 되도록 맞춰줍니다.
BASE = "import pandas as pd\nimport numpy as np\n"
LOAD_CUST = BASE + 'df = pd.read_csv("customers.csv")\n'

SETUP = {
    1: "",                                  # 1세트는 import부터 직접 친다
    2: LOAD_CUST,                           # df가 이미 있는 상태에서 시작
    3: LOAD_CUST,
    4: BASE, 5: BASE, 6: BASE, 7: BASE, 8: BASE, 9: BASE, 10: BASE,
    11: BASE, 12: BASE, 13: BASE, 14: BASE, 15: BASE, 16: BASE,
    17: BASE, 18: BASE, 19: BASE, 20: BASE,
}

SET_TITLES = [
    "데이터 분석 — 불러오기와 첫인상", "데이터 분석 — 기술통계와 결측",
    "데이터 분석 — 선택과 필터", "데이터 분석 — 집계", "데이터 분석 — 종합",
    "전처리 — 결측치", "전처리 — 중복·이상치", "전처리 — 인코딩",
    "전처리 — 스케일링", "전처리 — 분리", "전처리 — 분할 마무리",
    "모델링 — 분류 시작", "모델링 — 평가", "모델링 — 회귀",
    "모델링 — 여러 모델 비교", "모델링 — 성능 개선", "모델링 — 딥러닝",
    "실전 혼합 1", "실전 혼합 2", "실전 종합",
]
